### ISSUE TITLE
 The guide popup is behind the overlay

### ISSUE THREAD

**Issue by jatinthadani** [tnicola/ngx-joyride#4] opened 2018-06-29 07:33 UTC
I have use this to my angular 5 application with angular material 5.0.1 and I have done the exactly same as mentioned in the Readme file. I have imported the module inside my module.ts file and calling the startTour method from the component.ts file but the issue is **that guide popup is going behind the overlay**. Can you please help me.

**Comment by jatinthadani** [comment] 2018-06-29 13:59
No, I didn't do any customization of the joyride css. The **backdrop-container** it's z-index is creating the problem. Is there any way that we can resolve this issue.

**Comment by tnicola** [comment] 2018-06-29 20:28
That's really weird because I tested it across multiple browsers. Of course we can resolve this issue, can you provide more info about this? Like the browser you're using, some code snippets,...anything could be helpful.

In the meanwhile, I know that is not the most elegant solution but, try to use this in your css, if you've not tried yet:

```
joyride-step {
    z-index: 9999;
}
```

**Comment by tnicola** [comment] 2018-07-03 21:22
Ok, I found a way to reproduce this issue. It's a css issue/feature that I didn't consider, the z-index stack context. The z-index context is not absolute, there could be more than one, each one created thanks to some particular scenario and basically they are independent of each other. So, if for example you are setting `position: fixed; ` to an element, you're creating a local z-index context.

Here the link for the details: [https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) 

However, I should have found a way to solve this in the library, I think it will come with the next release.

**Comment by tnicola** [comment] 2018-07-10 17:33
Hi, this issue has been solved in [BugFix: Fixing z-index context bug](https://github.com/tnicola/ngx-joyride/commit/51685286c4c59b0acff4dec742558229475d27da) and it's now available in the 2.0.0 version.

**Comment by tnicola** [comment] 2018-07-21 16:20
Closing the issue.

**Closed** 2018-07-21 16:20 UTC
Labels: bug
