### ISSUE TITLE
Auto scroll error

### ISSUE THREAD

**Issue by achutkiran** [tnicola/ngx-joyride#31] opened 2019-01-22 21:56 UTC
Hi, my app has sticky toolbar and due to auto scroll the highlighted part is going behind toolbar. Any suggestions

**Comment by achutkiran** [comment] 2019-01-24 23:19
Hi @tnicola here is reproduction of bug scroll to bottom and click button
https://stackblitz.com/edit/ngx-joyride?file=src%2Findex.html

**Comment by tnicola** [comment] 2019-01-25 22:46
Thank you @achutkiran , that was really helpful!I have a solution in mind, I'll try it and I'll let you know when it will be fixed!

**Comment by tnicola** [comment] 2019-01-27 12:32
@achutkiran The bug has been fixed, try out the new ngx-joyride version. (2.2.4)

**Comment by achutkiran** [comment] 2019-01-28 16:23
It is not working in my application. i'll update the example to reflect it

**Comment by suvjunmd** [comment] 2019-01-28 16:55
Same problem in my project

**Comment by tnicola** [comment] 2019-01-28 23:18
Ok, I've found the issue. I need to test the new solution with all the use cases to be sure to not break the other functionalities and then I'll publish the new version. Thanks for the feedbacks!

**Comment by achutkiran** [comment] 2019-02-05 16:21
Hi @tnicola any update

**Comment by tnicola** [comment] 2019-02-05 20:36
@achutkiran Sorry about the delay. It should work correctly now. Try it out in the 2.2.5 version of the library: [ngx-joyride@2.2.5](https://www.npmjs.com/package/ngx-joyride/v/2.2.5).

**Closed** 2019-03-01 21:58 UTC
Labels: bug, need reproduction

**Comment by williamernesto** [comment] 2019-04-11 14:10
Hello, @tnicola, I recently discovered your package and I think it's amazing, but now I have the same problem. After reading the thread, i downloaded the version to version 2.2.5, but the problem continues, even in the most recent version. I'm using ng-zorro-antd UI. I do not reproduce the error because it is the same as in the previous examples.

**Comment by tnicola** [comment] 2019-04-11 22:05
Hi @williamernesto , thank you!Are you using also any scrolling libraries like perfect-scrollbar? You can follow this issue to stay updated #47.

**Comment by williamernesto** [comment] 2019-04-12 01:08
Hi @tnicola, the package work fine, I can set the options and the tour works, but when I click to start the tour, the page automatically scrolls down to the bottom. If I set the first step of the tour in an element in the bottom of the page it scrolls up perfectly, but the problem is when I set the step in the top of the page. I tested in a blank angular project, but it still behaves the same. Thank you for your quick reply. I hope you can find a way to fix it

**Comment by TahaAlkhatib** [comment] 2019-09-19 01:48
> Hi @tnicola, the package work fine, I can set the options and the tour works, but when I click to start the tour, the page automatically scrolls down to the bottom. If I set the first step of the tour in an element in the bottom of the page it scrolls up perfectly, but the problem is when I set the step in the top of the page. I tested in a blank angular project, but it still behaves the same. Thank you for your quick reply. I hope you can find a way to fix it

I have the same issue here , it some times scroll perfectly ,  but in other times it scroll to the bottom
I am using the 2.2.10 version with angular 8.

**Comment by vinh28193** [comment] 2019-10-03 04:50
> Hi @tnicola, the package work fine, I can set the options and the tour works, but when I click to start the tour, the page automatically scrolls down to the bottom. If I set the first step of the tour in an element in the bottom of the page it scrolls up perfectly, but the problem is when I set the step in the top of the page. I tested in a blank angular project, but it still behaves the same. Thank you for your quick reply. I hope you can find a way to fix it



> > Hi @tnicola, the package work fine, I can set the options and the tour works, but when I click to start the tour, the page automatically scrolls down to the bottom. If I set the first step of the tour in an element in the bottom of the page it scrolls up perfectly, but the problem is when I set the step in the top of the page. I tested in a blank angular project, but it still behaves the same. Thank you for your quick reply. I hope you can find a way to fix it
> 
> I have the same issue here , it some times scroll perfectly , but in other times it scroll to the bottom
> I am using the 2.2.10 version with angular 8.

me too, sir

**Comment by artdimaio** [comment] 2020-03-30 13:19
Same issue here, but only on small screens, like 360x640 or lower. The background gets darker but I can't see the content or the title, 'cause my element is far too low on the page. I'm using Angular 8.
`"@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/router": "8.2.14"`

**Comment by marianamendivil** [comment] 2020-04-23 17:14
Same here, I'm using Angular 7, I have a function that blocks the scrolling in the page before running the tour, but it still scrolls down to the bottom. Any updates?

**Comment by cazofeifa1616** [comment] 2020-05-04 17:13
I had a similar issue, using @2.2.5 version solved it, but no watingTime option nor closing programatically the tour funcionality are present anymore. This is a shame because now I have more issues than before. Going back to previous versions and deal with the scroll issue

**Comment by oksyassine** [comment] 2020-09-12 08:07
> Hi @tnicola, the package work fine, I can set the options and the tour works, but when I click to start the tour, the page automatically scrolls down to the bottom. If I set the first step of the tour in an element in the bottom of the page it scrolls up perfectly, but the problem is when I set the step in the top of the page. I tested in a blank angular project, but it still behaves the same. Thank you for your quick reply. I hope you can find a way to fix it

Same here using Angular 10, it scrolls always to the bottom of the page.

**Comment by Hellscream360** [comment] 2020-10-15 15:27
Hello, I have exactly the same problem (Angular 10).

**Comment by Gaurang-Savaliya** [comment] 2020-11-28 12:13
hi @tnicola, is there any way or property to stop auto scrolling page while starting tour?

**Comment by Lonedrive** [comment] 2021-07-02 09:42
Hello @tnicola any update on the topic?

**Comment by Kevlmt** [comment] 2023-06-30 09:43
any update in 2023 ? still have the problem...
